import type { ConformItem, ItemType } from "./types";
const TC=String.raw`\d{2}[:;]\d{2}[:;]\d{2}[:;]\d{2}`;
const RANGE_RE=new RegExp(`(${TC})\\s*[~～]\\s*(${TC})`);
const SOURCE_RE=new RegExp(`(\\d{4})\\s*版\\s*(R\\d+)\\s*(${TC})\\s*[~～]\\s*(${TC})`);
const normalizeTc=(tc:string)=>tc.replaceAll(";",":");
function classify(text:string,hasSource:boolean,hasRange:boolean):ItemType{if(/新增鏡頭/.test(text))return"new_shot";if(/OS/i.test(text))return/置換|改到|提前|改詞|拿掉/.test(text)?"replace":"os";if(/音效|鈴聲|廣播/.test(text))return"sound";if(/slow/i.test(text))return"slow";if(/重覆使用|重複使用/.test(text))return"reuse";if(/定格/.test(text))return"freeze";if(/置換|重配|改詞/.test(text))return"replace";if(hasSource&&hasRange)return"move";return"note"}
function tagsFor(text:string){const tags:string[]=[];const pairs:[RegExp,string][]=[[/slow/i,"SLOW"],[/重覆使用|重複使用/,"REUSE"],[/新增鏡頭/,"NEW SHOT"],[/OS/i,"OS"],[/音效|鈴聲|廣播/,"SFX"],[/置換|重配/,"REPLACE"],[/定格/,"FREEZE"],[/放大/,"ZOOM"]];for(const [re,tag] of pairs)if(re.test(text))tags.push(tag);return tags}
function compactNote(raw:string,range?:RegExpMatchArray|null,source?:RegExpMatchArray|null,point?:RegExpMatchArray|null){let note=raw;if(range)note=note.replace(range[0],"");if(source)note=note.replace(source[0],"");if(point&&!range)note=note.replace(point[0],"");return note.replace(/^\s*是\s*/,"").replace(/\s+/g," ").trim()}
export function parseAdjustmentText(rawText:string):ConformItem[]{const physical=rawText.split(/\r?\n/).map(s=>s.trim()).filter(Boolean);const merged:string[]=[];for(const line of physical){if(/^\d{2}[:;]/.test(line))merged.push(line);else if(merged.length)merged[merged.length-1]+=" "+line}const items:ConformItem[]=[];let order=1;for(const raw of merged){const warnings:string[]=[];const parseText=raw.replaceAll("；",";");if(parseText.includes(";"))warnings.push("原始文件的時間碼含分號；解析時已暫時視為冒號，請人工確認。");const range=parseText.match(RANGE_RE);const source=parseText.match(SOURCE_RE);let destination;let pointTc;let point:RegExpMatchArray|null=null;if(range)destination={in:normalizeTc(range[1]),out:normalizeTc(range[2])};else{point=parseText.match(new RegExp(TC));if(point)pointTc=normalizeTc(point[0])}const sourceVersion=source?`${source[1]} ${source[2]}`:undefined;const sourceRange=source?{in:normalizeTc(source[3]),out:normalizeTc(source[4])}:undefined;if(!destination&&!pointTc)continue;const type=classify(parseText,!!sourceRange,!!destination);items.push({id:`item-${String(order).padStart(3,"0")}`,order,type,status:"pending",destination,pointTc,sourceVersion,source:sourceRange,note:compactNote(raw,range,source,point),rawText:raw,tags:tagsFor(parseText),warnings});order++}return items}
