import { useEffect,useMemo,useRef,useState } from "react";
import type { KeyboardEvent,ReactNode } from "react";
import mammoth from "mammoth";
import { open } from "@tauri-apps/plugin-dialog";
import { readFile } from "@tauri-apps/plugin-fs";
import { register,unregisterAll } from "@tauri-apps/plugin-global-shortcut";
import { parseAdjustmentText } from "./lib/parser";
import { applyNameTemplate,rangeText } from "./lib/template";
import { checkNuendoConnection,copyText,openMacAccessibilitySettings,sendNuendoShortcut,setWindowAlwaysOnTop } from "./lib/tauri";
import type { AppSettings,ConformItem,ProjectState,ShortcutMap } from "./lib/types";
const mac:ShortcutMap={cut:"cmd+x",copy:"cmd+c",paste:"cmd+v",undo:"cmd+z",redo:"cmd+shift+z",insertSilence:"cmd+shift+e",splitLoop:"",selectInLoop:""};
const win:ShortcutMap={cut:"ctrl+x",copy:"ctrl+c",paste:"ctrl+v",undo:"ctrl+z",redo:"ctrl+shift+z",insertSilence:"ctrl+shift+e",splitLoop:"",selectInLoop:""};
const defaultSettings:AppSettings={platformMode:"auto",targetAppMac:"Nuendo 15",targetProcessWindows:"Nuendo",nameTemplate:"{source_range}",fps:24,fpsConfirmed:false,alwaysOnTop:false,shortcutsMac:mac,shortcutsWindows:win};
const storageKey="nuendo-conform-helper-v1";
function loadInitial():ProjectState{try{const s=localStorage.getItem(storageKey);if(s){const saved=JSON.parse(s) as Partial<ProjectState>;return{...saved,name:saved.name??"未命名專案",items:saved.items??[],settings:{...defaultSettings,...saved.settings,shortcutsMac:{...mac,...saved.settings?.shortcutsMac},shortcutsWindows:{...win,...saved.settings?.shortcutsWindows}}}}}catch{}return{name:"未命名專案",items:[],settings:{...defaultSettings,shortcutsMac:{...mac},shortcutsWindows:{...win}}}}
const labels:Record<ConformItem["type"],string>={move:"NORMAL",slow:"SLOW",reuse:"REUSE",new_shot:"NEW SHOT",os:"OS",sound:"SFX",replace:"REPLACE",freeze:"FREEZE",note:"NOTE"};
function sourceMarker(version?:string){if(!version)return"";const match=version.trim().match(/^(\d{4})\s+(R\d+)$/);return match?`是 ${match[1]} 版 ${match[2]}`:`是 ${version}`}
function sourceTone(version?:string){return version?.trim().endsWith("R3")?"r3":""}
const currentPlatform=():"mac"|"windows"=>navigator.platform.toLowerCase().includes("mac")?"mac":"windows";
export default function App(){const[project,setProject]=useState<ProjectState>(loadInitial);const[filter,setFilter]=useState<"all"|"pending"|"done">("pending");const[search,setSearch]=useState("");const[pasteText,setPasteText]=useState("");const[toast,setToast]=useState("");const[showSettings,setShowSettings]=useState(false);const[connectionStatus,setConnectionStatus]=useState("");const[shortcutStatus,setShortcutStatus]=useState("");const[windowStatus,setWindowStatus]=useState("");const[globalShortcutStatus,setGlobalShortcutStatus]=useState("");const projectRef=useRef(project);
useEffect(()=>localStorage.setItem(storageKey,JSON.stringify(project)),[project]);
useEffect(()=>{projectRef.current=project},[project]);
useEffect(()=>{let active=true;void setWindowAlwaysOnTop(project.settings.alwaysOnTop).then(()=>{if(active)setWindowStatus(project.settings.alwaysOnTop?"永遠置頂：已開啟":"永遠置頂：已關閉")}).catch(error=>{if(active){const message=error instanceof Error?error.message:String(error);setWindowStatus(message);setToast(message)}});return()=>{active=false}},[project.settings.alwaysOnTop]);
const filtered=useMemo(()=>project.items.filter(i=>{if(filter!=="all"&&i.status!==filter)return false;if(!search.trim())return true;const q=search.toLowerCase();return[i.rawText,i.note,i.sourceVersion,i.source?.in,i.source?.out,i.destination?.in,i.destination?.out,i.pointTc].filter(Boolean).some(x=>String(x).toLowerCase().includes(q))}),[project.items,filter,search]);
const current=project.items.find(x=>x.id===project.currentId)??filtered[0]??project.items[0];const doneCount=project.items.filter(x=>x.status==="done").length;
const flash=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(""),1400)};const patchItem=(id:string,patch:Partial<ConformItem>)=>setProject(p=>({...p,items:p.items.map(x=>x.id===id?{...x,...patch}:x)}));const selectItem=(id:string)=>setProject(p=>({...p,currentId:id}));
async function copy(v:string,l:string){if(!v)return;await copyText(v);flash(`已複製：${l}`)}
function goRelative(d:number){if(!current||!filtered.length)return;const idx=filtered.findIndex(x=>x.id===current.id);const n=filtered[Math.min(Math.max(idx+d,0),filtered.length-1)];if(n)selectItem(n.id)}
function completeAndNext(){if(!current)return;patchItem(current.id,{status:"done"});const src=filtered.length?filtered:project.items;const idx=src.findIndex(x=>x.id===current.id);const n=src.slice(idx+1).find(x=>x.status!=="done");if(n)selectItem(n.id)}
async function importDocx(){try{const selected=await open({multiple:false,filters:[{name:"Word 文件",extensions:["docx"]}]});if(!selected||Array.isArray(selected))return;const bytes=await readFile(selected);const ab=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength);const result=await mammoth.extractRawText({arrayBuffer:ab});const items=parseAdjustmentText(result.value);if(!items.length)throw new Error("文件中找不到可辨識的時間碼項目。");setProject(p=>({...p,name:selected.split(/[\\/]/).pop()?.replace(/\.docx$/i,"")||"Conform Project",items,currentId:items[0]?.id,importedAt:new Date().toISOString()}));flash(`已解析 ${items.length} 筆`)}catch(e){flash(e instanceof Error?e.message:"DOCX 匯入失敗")}}
function parsePasted(){const items=parseAdjustmentText(pasteText);if(!items.length){flash("貼上的文字中找不到可辨識的時間碼項目");return}setProject(p=>({...p,items,currentId:items[0]?.id,importedAt:new Date().toISOString()}));flash(`已解析 ${items.length} 筆`)}
const platform=project.settings.platformMode==="auto"?currentPlatform():project.settings.platformMode;const shortcuts=platform==="mac"?project.settings.shortcutsMac:project.settings.shortcutsWindows;
async function runShortcut(k:keyof ShortcutMap){setShortcutStatus(`正在送出 ${k}…`);try{await sendNuendoShortcut(shortcuts[k],project.settings.targetAppMac,project.settings.targetProcessWindows);const message=`已送出：${k}（${shortcuts[k]}）`;setShortcutStatus(message);flash(message)}catch(e){const message=e instanceof Error?e.message:"快捷鍵執行失敗";setShortcutStatus(message);flash(message)}}
async function testConnection(){setConnectionStatus("連接中…");try{const target=await checkNuendoConnection(project.settings.targetAppMac,project.settings.targetProcessWindows);const message=`已連接：${target||"Nuendo"}；快捷鍵權限正常`;setConnectionStatus(message);flash(message)}catch(e){const message=e instanceof Error?e.message:String(e);setConnectionStatus(message);flash(message)}}
async function openAccessibility(){try{await openMacAccessibilitySettings();setConnectionStatus("已開啟輔助使用設定。允許本 App 後請完全結束並重新開啟。") }catch(e){setConnectionStatus(e instanceof Error?e.message:String(e))}}
useEffect(()=>{const setup=async()=>{try{await unregisterAll();const current=()=>projectRef.current.items.find(x=>x.id===projectRef.current.currentId)??projectRef.current.items[0];await register("Alt+1",()=>{const i=current();if(i?.source?.in)void copyText(i.source.in)});await register("Alt+2",()=>{const i=current();if(i?.source?.out)void copyText(i.source.out)});await register("Alt+3",()=>{const i=current();if(i?.source)void copyText(rangeText(i.source.in,i.source.out))});setGlobalShortcutStatus("全域 Quick Copy：已啟用")}catch(e){setGlobalShortcutStatus(`全域 Quick Copy 無法啟用：${e instanceof Error?e.message:String(e)}`)}};void setup();return()=>{void unregisterAll()}},[]);
const srcRange=current?.source?rangeText(current.source.in,current.source.out):"";const templateText=current?applyNameTemplate(project.settings.nameTemplate,current):"";
return <div className="app-shell"><header className="topbar"><div><div className="eyebrow">NUENDO CONFORM HELPER</div><input className="project-name" value={project.name} onChange={e=>setProject(p=>({...p,name:e.target.value}))}/></div><div className="top-actions"><div className="progress"><strong>{doneCount}</strong> / {project.items.length}</div><button className={project.settings.alwaysOnTop?"pin-active":"ghost"} onClick={()=>setProject(p=>({...p,settings:{...p.settings,alwaysOnTop:!p.settings.alwaysOnTop}}))}>{project.settings.alwaysOnTop?"📌 置頂中":"置頂"}</button><button onClick={importDocx}>匯入 DOCX</button><button className="ghost" onClick={()=>setShowSettings(v=>!v)}>設定</button></div></header>
{!project.settings.fpsConfirmed&&<div className="warning-banner">文件本身沒有明示 FPS。現在暫設 {project.settings.fps} fps；需要計算格數/長度前請先確認。<button onClick={()=>setProject(p=>({...p,settings:{...p.settings,fpsConfirmed:true}}))}>我已確認</button></div>}
{showSettings&&<section className="settings-panel">
  <Field label="平台"><select value={project.settings.platformMode} onChange={e=>setProject(p=>({...p,settings:{...p.settings,platformMode:e.target.value as AppSettings["platformMode"]}}))}><option value="auto">自動</option><option value="mac">macOS</option><option value="windows">Windows</option></select></Field>
  <Field label="macOS Nuendo App 名稱"><input value={project.settings.targetAppMac} onChange={e=>setProject(p=>({...p,settings:{...p.settings,targetAppMac:e.target.value}}))}/></Field>
  <Field label="Windows Nuendo Process"><input value={project.settings.targetProcessWindows} onChange={e=>setProject(p=>({...p,settings:{...p.settings,targetProcessWindows:e.target.value}}))}/></Field>
  <div className="connection-panel"><div><strong>連接與權限流程</strong><small>先找到並切換到 Nuendo，再由 App 原生送出對應系統快捷鍵。macOS 必須允許本 App 使用輔助使用；Windows 必須與 Nuendo 使用相同權限層級。</small></div><div className="connection-actions"><button type="button" onClick={testConnection}>測試連接</button>{platform==="mac"&&<button type="button" className="ghost" onClick={openAccessibility}>開啟輔助使用設定</button>}</div>{connectionStatus&&<div className="connection-status">{connectionStatus}</div>}</div>
  <Field label="Loop 命名模板"><input value={project.settings.nameTemplate} onChange={e=>setProject(p=>({...p,settings:{...p.settings,nameTemplate:e.target.value}}))}/><small>{"{source_range} {source_version} {source_in} {source_out} {new_range} {note}"}</small></Field>
  <Field label="FPS"><input type="number" min={1} value={project.settings.fps} onChange={e=>setProject(p=>({...p,settings:{...p.settings,fps:Number(e.target.value),fpsConfirmed:false}}))}/></Field>
  <label className="always-top-toggle"><input type="checkbox" checked={project.settings.alwaysOnTop} onChange={e=>setProject(p=>({...p,settings:{...p.settings,alwaysOnTop:e.target.checked}}))}/><span><strong>永遠置頂</strong><small>{windowStatus||"讓工具視窗保持在 Nuendo 與其他視窗上方。"}</small></span></label>
  <ShortcutEditor platform={platform} platformLabel={platform==="mac"?"macOS":"Windows"} shortcuts={shortcuts} onChange={(k,v)=>setProject(p=>{const settings={...p.settings};if(platform==="mac")settings.shortcutsMac={...settings.shortcutsMac,[k]:v};else settings.shortcutsWindows={...settings.shortcutsWindows,[k]:v};return{...p,settings}})}/>
</section>}
<main className="workspace"><aside className="sidebar"><div className="filters"><input placeholder="搜尋 TC / 備註 / 版本" value={search} onChange={e=>setSearch(e.target.value)}/><div className="segmented">{(["pending","all","done"] as const).map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x==="pending"?"未完成":x==="done"?"完成":"全部"}</button>)}</div></div><div className="item-list">{filtered.map(i=><button key={i.id} className={`item-row ${current?.id===i.id?"selected":""}`} onClick={()=>selectItem(i.id)}><span className={`type-dot ${i.type}`}/><span className="item-main"><strong>#{String(i.order).padStart(2,"0")} {labels[i.type]}</strong><small>{i.destination?rangeText(i.destination.in,i.destination.out):i.pointTc}</small>{i.sourceVersion&&<small className={`source-list-label ${sourceTone(i.sourceVersion)}`}>{sourceMarker(i.sourceVersion)}</small>}</span><span className={`status ${i.status}`}>{i.status==="done"?"✓":""}</span></button>)}</div><div className="paste-box"><textarea placeholder="也可以直接貼上調整說明文字..." value={pasteText} onChange={e=>setPasteText(e.target.value)}/><button onClick={parsePasted} disabled={!pasteText.trim()}>解析貼上文字</button></div></aside>
<section className="detail">{!current?<div className="empty">請匯入 DOCX 或貼上調整說明文字。</div>:<><div className="card header-card"><div><div className={`pill ${current.type}`}>{labels[current.type]}</div><h2>#{String(current.order).padStart(2,"0")}</h2>{current.sourceVersion&&<div className={`source-marker ${sourceTone(current.sourceVersion)}`}>{sourceMarker(current.sourceVersion)}</div>}</div><div className="tags">{current.tags.map(t=><span key={t}>{t}</span>)}</div></div><TimeCard title="新版位置" inTc={current.destination?.in} outTc={current.destination?.out} pointTc={current.pointTc} onCopy={copy} rangeLabel="新版整段"/>
<div className="card"><div className="card-title"><span>來源標注</span><strong className={`source-inline ${sourceTone(current.sourceVersion)}`}>{sourceMarker(current.sourceVersion)||"—"}</strong></div>{current.source?<><div className="tc-pair"><button onClick={()=>copy(current.source!.in,"來源 IN")}>{current.source.in}</button><span>→</span><button onClick={()=>copy(current.source!.out,"來源 OUT")}>{current.source.out}</button></div><div className="copy-grid"><button onClick={()=>copy(srcRange,"來源整段")}>複製整段 TC</button><button onClick={()=>copy(`${current.sourceVersion??""} ${srcRange}`.trim(),"版本＋整段")}>複製版本＋整段</button></div></>:<div className="muted">這筆沒有舊版來源區間。</div>}</div>
<div className="card"><div className="card-title"><span>Loop / 文字命名</span></div><code className="template-preview">{templateText||"—"}</code><div className="copy-grid three"><button onClick={()=>copy(templateText,"Loop 名稱")} disabled={!templateText}>複製 Loop 名稱</button><button onClick={()=>copy(current.rawText,"原始整行")}>複製原始整行</button><button onClick={()=>copy(current.note,"備註")} disabled={!current.note}>複製備註</button></div></div>
{(current.note||current.warnings.length>0)&&<div className="card note-card">{current.note&&<p>{current.note}</p>}{current.warnings.map(w=><div className="warning-text" key={w}>{w}</div>)}</div>}
<div className="card action-card"><div className="card-title"><span>Nuendo 快捷操作</span><small>{platform==="mac"?"macOS":"Windows"}</small></div><div className="action-grid"><button onClick={()=>runShortcut("splitLoop")}>Split Loop</button><button onClick={()=>runShortcut("selectInLoop")}>Select In Loop</button><button onClick={()=>runShortcut("cut")}>Cut</button><button onClick={()=>runShortcut("copy")}>Copy</button><button onClick={()=>runShortcut("paste")}>Paste</button><button onClick={()=>runShortcut("insertSilence")}>Insert Silence</button><button onClick={()=>runShortcut("undo")}>Undo</button><button onClick={()=>runShortcut("redo")}>Redo</button></div><div className="hint">按鈕會先切回 Nuendo，再送出你設定的快捷鍵。Split Loop / Select In Loop 預設留空，請依你的 Nuendo Key Commands 設定。</div>{shortcutStatus&&<div className="shortcut-status">{shortcutStatus}</div>}</div>
<div className="nav-bar"><button onClick={()=>goRelative(-1)}>← 上一筆</button><button className="secondary" onClick={()=>patchItem(current.id,{status:current.status==="skipped"?"pending":"skipped"})}>{current.status==="skipped"?"取消略過":"略過"}</button><button className="primary" onClick={completeAndNext}>✓ 完成並下一筆</button><button onClick={()=>goRelative(1)}>下一筆 →</button></div><div className="global-hint">全域 Quick Copy：Alt/Option+1＝來源 IN、Alt/Option+2＝來源 OUT、Alt/Option+3＝來源整段。{globalShortcutStatus&&<>　{globalShortcutStatus}</>}</div></>}</section></main>{toast&&<div className="toast">{toast}</div>}</div>}
function Field({label,children}:{label:string;children:ReactNode}){return <div className="field"><label>{label}</label>{children}</div>}
function TimeCard({title,inTc,outTc,pointTc,onCopy,rangeLabel}:{title:string;inTc?:string;outTc?:string;pointTc?:string;onCopy:(v:string,l:string)=>void;rangeLabel:string}){const range=inTc&&outTc?rangeText(inTc,outTc):"";return <div className="card"><div className="card-title"><span>{title}</span></div>{pointTc?<div className="tc-single"><button onClick={()=>onCopy(pointTc,title)}>{pointTc}</button></div>:<><div className="tc-pair"><button onClick={()=>onCopy(inTc??"",`${title} IN`)}>{inTc??"—"}</button><span>→</span><button onClick={()=>onCopy(outTc??"",`${title} OUT`)}>{outTc??"—"}</button></div><button className="wide-copy" onClick={()=>onCopy(range,rangeLabel)} disabled={!range}>複製整段：{range||"—"}</button></>}</div>}
function recordedShortcut(event:KeyboardEvent<HTMLInputElement>,platform:"mac"|"windows"){
  const named:Record<string,string>={Enter:"enter",Return:"enter",Backspace:"backspace",Delete:"delete",Tab:"tab",Escape:"escape",Space:"space",ArrowLeft:"left",ArrowRight:"right",ArrowUp:"up",ArrowDown:"down",Home:"home",End:"end",PageUp:"pageup",PageDown:"pagedown",Insert:"insert"};
  const raw=event.key;
  if(raw==="Dead"||["Control","Alt","Shift","Meta"].includes(raw))return"";
  if(platform==="windows"&&event.metaKey)return"";
  const codeKey=event.code.match(/^Key([A-Z])$/)?.[1]?.toLowerCase()??event.code.match(/^(?:Digit|Numpad)([0-9])$/)?.[1];
  const key=named[raw]??codeKey??(raw.length===1?raw.toLowerCase():raw.toLowerCase());
  const modifiers:string[]=[];
  if(platform==="mac"&&event.metaKey)modifiers.push("cmd");
  if(platform==="windows"&&event.ctrlKey)modifiers.push("ctrl");
  if(event.ctrlKey&&platform==="mac")modifiers.push("ctrl");
  if(event.altKey)modifiers.push("alt");
  if(event.shiftKey)modifiers.push("shift");
  return[...modifiers,key].join("+");
}
function ShortcutEditor({platform,platformLabel,shortcuts,onChange}:{platform:"mac"|"windows";platformLabel:string;shortcuts:ShortcutMap;onChange:(k:keyof ShortcutMap,v:string)=>void}){const pairs:[keyof ShortcutMap,string][]=[["cut","Cut"],["copy","Copy"],["paste","Paste"],["undo","Undo"],["redo","Redo"],["insertSilence","Insert Silence"],["splitLoop","Split Loop"],["selectInLoop","Select In Loop"]];const[recording,setRecording]=useState<keyof ShortcutMap|null>(null);const inputRefs=useRef<Partial<Record<keyof ShortcutMap,HTMLInputElement>>>({});useEffect(()=>{if(recording)inputRefs.current[recording]?.focus()},[recording]);return <div className="shortcut-editor"><div className="shortcut-heading"><h3>{platformLabel} 快捷鍵</h3><small>按「錄製」後直接按下 Nuendo Key Command；Esc 取消。</small></div>{pairs.map(([k,l])=><div className="shortcut-row" key={k}><span>{l}</span><input ref={node=>{if(node)inputRefs.current[k]=node}} value={shortcuts[k]} placeholder="例如 ctrl+shift+e" onChange={e=>onChange(k,e.target.value)} onKeyDown={event=>{if(recording!==k)return;event.preventDefault();if(event.key==="Escape"&&!event.metaKey&&!event.ctrlKey&&!event.altKey&&!event.shiftKey){setRecording(null);return}const value=recordedShortcut(event,platform);if(value){onChange(k,value);setRecording(null)}}}/><button type="button" className={recording===k?"recording":""} onClick={()=>setRecording(recording===k?null:k)}>{recording===k?"按鍵中…":"錄製"}</button></div>)}</div>}
